/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsEnum,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { EnumPickupCashStatus } from "./EnumPickupCashStatus";
import { EnumPickupPickupStatus } from "./EnumPickupPickupStatus";
import { EnumPickupScrapType } from "./EnumPickupScrapType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
@InputType()
class PickupUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  agentId?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumPickupCashStatus,
  })
  @IsEnum(EnumPickupCashStatus)
  @IsOptional()
  @Field(() => EnumPickupCashStatus, {
    nullable: true,
  })
  cashStatus?: "Pending" | "Payed";

  @ApiProperty({
    required: false,
    enum: EnumPickupPickupStatus,
  })
  @IsEnum(EnumPickupPickupStatus)
  @IsOptional()
  @Field(() => EnumPickupPickupStatus, {
    nullable: true,
  })
  pickupStatus?: "Pending" | "Cancelled" | "Filled";

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rateForScrap?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  remuneration?: number;

  @ApiProperty({
    required: false,
    enum: EnumPickupScrapType,
  })
  @IsEnum(EnumPickupScrapType)
  @IsOptional()
  @Field(() => EnumPickupScrapType, {
    nullable: true,
  })
  scrapType?: "Paper" | "Metal" | "Plastic" | "Glass";

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  scrapWeight?: number;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  uuid?: UserWhereUniqueInput;
}
export { PickupUpdateInput };
