/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PickupService } from "../pickup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PickupCreateInput } from "./PickupCreateInput";
import { PickupWhereInput } from "./PickupWhereInput";
import { PickupWhereUniqueInput } from "./PickupWhereUniqueInput";
import { PickupFindManyArgs } from "./PickupFindManyArgs";
import { PickupUpdateInput } from "./PickupUpdateInput";
import { Pickup } from "./Pickup";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PickupControllerBase {
  constructor(
    protected readonly service: PickupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Pickup",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pickup })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: PickupCreateInput): Promise<Pickup> {
    return await this.service.create({
      data: {
        ...data,

        uuid: {
          connect: data.uuid,
        },
      },
      select: {
        agentId: true,
        cashStatus: true,
        createdAt: true,
        id: true,
        pickupStatus: true,
        rateForScrap: true,
        remuneration: true,
        scrapType: true,
        scrapWeight: true,
        updatedAt: true,

        uuid: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Pickup",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Pickup] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PickupFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Pickup[]> {
    const args = plainToClass(PickupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        agentId: true,
        cashStatus: true,
        createdAt: true,
        id: true,
        pickupStatus: true,
        rateForScrap: true,
        remuneration: true,
        scrapType: true,
        scrapWeight: true,
        updatedAt: true,

        uuid: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Pickup",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pickup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PickupWhereUniqueInput
  ): Promise<Pickup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        agentId: true,
        cashStatus: true,
        createdAt: true,
        id: true,
        pickupStatus: true,
        rateForScrap: true,
        remuneration: true,
        scrapType: true,
        scrapWeight: true,
        updatedAt: true,

        uuid: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Pickup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pickup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PickupWhereUniqueInput,
    @common.Body() data: PickupUpdateInput
  ): Promise<Pickup | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          uuid: {
            connect: data.uuid,
          },
        },
        select: {
          agentId: true,
          cashStatus: true,
          createdAt: true,
          id: true,
          pickupStatus: true,
          rateForScrap: true,
          remuneration: true,
          scrapType: true,
          scrapWeight: true,
          updatedAt: true,

          uuid: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Pickup",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pickup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PickupWhereUniqueInput
  ): Promise<Pickup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          agentId: true,
          cashStatus: true,
          createdAt: true,
          id: true,
          pickupStatus: true,
          rateForScrap: true,
          remuneration: true,
          scrapType: true,
          scrapWeight: true,
          updatedAt: true,

          uuid: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
