/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsEnum,
  IsDate,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { EnumPickupCashStatus } from "./EnumPickupCashStatus";
import { Type } from "class-transformer";
import { EnumPickupPickupStatus } from "./EnumPickupPickupStatus";
import { EnumPickupScrapType } from "./EnumPickupScrapType";
import { User } from "../../user/base/User";
@ObjectType()
class Pickup {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  agentId!: string | null;

  @ApiProperty({
    required: true,
    enum: EnumPickupCashStatus,
  })
  @IsEnum(EnumPickupCashStatus)
  @Field(() => EnumPickupCashStatus, {
    nullable: true,
  })
  cashStatus?: "Pending" | "Payed";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    enum: EnumPickupPickupStatus,
  })
  @IsEnum(EnumPickupPickupStatus)
  @Field(() => EnumPickupPickupStatus, {
    nullable: true,
  })
  pickupStatus?: "Pending" | "Cancelled" | "Filled";

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  rateForScrap!: number;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  remuneration!: number;

  @ApiProperty({
    required: true,
    enum: EnumPickupScrapType,
  })
  @IsEnum(EnumPickupScrapType)
  @Field(() => EnumPickupScrapType, {
    nullable: true,
  })
  scrapType?: "Paper" | "Metal" | "Plastic" | "Glass";

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  scrapWeight!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  uuid?: User;
}
export { Pickup };
