/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { EnumPickupCashStatus } from "./EnumPickupCashStatus";
import { StringFilter } from "../../util/StringFilter";
import { EnumPickupPickupStatus } from "./EnumPickupPickupStatus";
import { EnumPickupScrapType } from "./EnumPickupScrapType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class PickupWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  agentId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumPickupCashStatus,
  })
  @IsEnum(EnumPickupCashStatus)
  @IsOptional()
  @Field(() => EnumPickupCashStatus, {
    nullable: true,
  })
  cashStatus?: "Pending" | "Payed";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumPickupPickupStatus,
  })
  @IsEnum(EnumPickupPickupStatus)
  @IsOptional()
  @Field(() => EnumPickupPickupStatus, {
    nullable: true,
  })
  pickupStatus?: "Pending" | "Cancelled" | "Filled";

  @ApiProperty({
    required: false,
    enum: EnumPickupScrapType,
  })
  @IsEnum(EnumPickupScrapType)
  @IsOptional()
  @Field(() => EnumPickupScrapType, {
    nullable: true,
  })
  scrapType?: "Paper" | "Metal" | "Plastic" | "Glass";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  uuid?: UserWhereUniqueInput;
}
export { PickupWhereInput };
