/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { PickupCreateNestedManyWithoutUsersInput } from "./PickupCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { TotalStatWhereUniqueInput } from "../../totalStat/base/TotalStatWhereUniqueInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  emailId!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  phoneNumber!: string;

  @ApiProperty({
    required: false,
    type: () => PickupCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PickupCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PickupCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  pickups?: PickupCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: false,
    type: () => TotalStatWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TotalStatWhereUniqueInput)
  @IsOptional()
  @Field(() => TotalStatWhereUniqueInput, {
    nullable: true,
  })
  totalStats?: TotalStatWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  upiId!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
