/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { Public } from "../../decorators/public.decorator";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { PickupFindManyArgs } from "../../pickup/base/PickupFindManyArgs";
import { Pickup } from "../../pickup/base/Pickup";
import { PickupWhereUniqueInput } from "../../pickup/base/PickupWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: {
        ...data,

        totalStats: data.totalStats
          ? {
              connect: data.totalStats,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        emailId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        roles: true,

        totalStats: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        upiId: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UserFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        emailId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        roles: true,

        totalStats: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        upiId: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        emailId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        roles: true,

        totalStats: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        upiId: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          totalStats: data.totalStats
            ? {
                connect: data.totalStats,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          emailId: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          roles: true,

          totalStats: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          upiId: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          emailId: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          roles: true,

          totalStats: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          upiId: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Pickup",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/pickups")
  @ApiNestedQuery(PickupFindManyArgs)
  async findManyPickups(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Pickup[]> {
    const query = plainToClass(PickupFindManyArgs, request.query);
    const results = await this.service.findPickups(params.id, {
      ...query,
      select: {
        agentId: true,
        cashStatus: true,
        createdAt: true,
        id: true,
        pickupStatus: true,
        rateForScrap: true,
        remuneration: true,
        scrapType: true,
        scrapWeight: true,
        updatedAt: true,

        uuid: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/pickups")
  async connectPickups(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PickupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pickups: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/pickups")
  async updatePickups(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PickupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pickups: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/pickups")
  async disconnectPickups(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PickupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pickups: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
